version: "3.3"
services:
  freshers_portal_backend:
    container_name: freshers_portal_backend
    image: freshers_portal_backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
       - ./uploads:/usr/src/app/backend/uploads 
    ports:
      - "3499:5000"
    env_file:
      - .env
    networks:
      - backend_welfare-board-strapi



networks:
  backend_welfare-board-strapi:
    external: true